export const sportmonksLeagues = [
  {
    "id": 570,
    "sport_id": 1,
    "country_id": 32,
    "name": "Copa Del Rey",
    "active": true,
    "short_code": null,
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/26/570.png",
    "type": "league",
    "sub_type": "domestic_cup",
    "last_played_at": "2023-05-06 20:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 444,
    "sport_id": 1,
    "country_id": 1578,
    "name": "Eliteserien",
    "active": true,
    "short_code": "NOR TL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/28/444.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 17:15:00",
    "category": 3,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 27,
    "sport_id": 1,
    "country_id": 462,
    "name": "Carabao Cup",
    "active": true,
    "short_code": null,
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/27/27.png",
    "type": "league",
    "sub_type": "domestic_cup",
    "last_played_at": "2023-09-27 19:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 181,
    "sport_id": 1,
    "country_id": 143,
    "name": "Admiral Bundesliga",
    "active": true,
    "short_code": "AUT BL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/181.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 15:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 486,
    "sport_id": 1,
    "country_id": 227,
    "name": "Premier League",
    "active": true,
    "short_code": null,
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/6/486.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 16:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 384,
    "sport_id": 1,
    "country_id": 251,
    "name": "Serie A",
    "active": true,
    "short_code": "ITA SA",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/0/384.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 18:45:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 453,
    "sport_id": 1,
    "country_id": 2,
    "name": "Ekstraklasa",
    "active": true,
    "short_code": "POL E",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/5/453.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 17:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 600,
    "sport_id": 1,
    "country_id": 404,
    "name": "Super Lig",
    "active": true,
    "short_code": "TUR SL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/24/600.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 17:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 244,
    "sport_id": 1,
    "country_id": 266,
    "name": "1. HNL",
    "active": true,
    "short_code": null,
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/20/244.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 16:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 82,
    "sport_id": 1,
    "country_id": 11,
    "name": "Bundesliga",
    "active": true,
    "short_code": "GER BI",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/82.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 15:30:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 609,
    "sport_id": 1,
    "country_id": 86,
    "name": "Premier League",
    "active": true,
    "short_code": null,
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/1/609.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 14:00:00",
    "category": 3,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 501,
    "sport_id": 1,
    "country_id": 1161,
    "name": "Premiership",
    "active": true,
    "short_code": "SCO P",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/501.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-09-30 14:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 591,
    "sport_id": 1,
    "country_id": 62,
    "name": "Super League",
    "active": true,
    "short_code": null,
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/15/591.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 14:30:00",
    "category": 3,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 208,
    "sport_id": 1,
    "country_id": 556,
    "name": "Pro League",
    "active": true,
    "short_code": "BEL FDA",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/16/208.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 17:15:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 567,
    "sport_id": 1,
    "country_id": 32,
    "name": "La Liga 2",
    "active": true,
    "short_code": "ESP S",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/23/567.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-03 19:30:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 462,
    "sport_id": 1,
    "country_id": 20,
    "name": "Liga Portugal",
    "active": true,
    "short_code": "PRT PL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/14/462.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 19:15:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 564,
    "sport_id": 1,
    "country_id": 32,
    "name": "La Liga",
    "active": true,
    "short_code": "ESP PL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/20/564.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 19:00:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 1371,
    "sport_id": 1,
    "country_id": 556,
    "name": "UEFA Europa League Play-offs",
    "active": true,
    "short_code": null,
    "image_path":
      "https://cdn.sportmonks.com/images/soccer/leagues/27/1371.png",
    "type": "league",
    "sub_type": "play-offs",
    "last_played_at": "2019-05-26 14:42:38",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 8,
    "sport_id": 1,
    "country_id": 462,
    "name": "Premier League",
    "active": true,
    "short_code": "UK PL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/8/8.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-03 18:30:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 72,
    "sport_id": 1,
    "country_id": 38,
    "name": "Eredivisie",
    "active": true,
    "short_code": "NLD E",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/72.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 14:45:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 301,
    "sport_id": 1,
    "country_id": 17,
    "name": "Ligue 1",
    "active": true,
    "short_code": "FRA L1",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/13/301.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 18:45:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 390,
    "sport_id": 1,
    "country_id": 251,
    "name": "Coppa Italia",
    "active": true,
    "short_code": "ITA Coppa",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/6/390.png",
    "type": "league",
    "sub_type": "domestic_cup",
    "last_played_at": "2023-08-14 19:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 387,
    "sport_id": 1,
    "country_id": 251,
    "name": "Serie B",
    "active": true,
    "short_code": "ITA SB",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/3/387.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-01 16:30:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 271,
    "sport_id": 1,
    "country_id": 320,
    "name": "Superliga",
    "active": true,
    "short_code": "DNK SL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/271.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 17:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 573,
    "sport_id": 1,
    "country_id": 47,
    "name": "Allsvenskan",
    "active": true,
    "short_code": "SWE AL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/29/573.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-02 17:10:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 2,
    "sport_id": 1,
    "country_id": 41,
    "name": "Champions League",
    "active": true,
    "short_code": "UEFA CL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/2.png",
    "type": "league",
    "sub_type": "cup_international",
    "last_played_at": "2023-10-03 19:00:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 2286,
    "sport_id": 1,
    "country_id": 41,
    "name": "Europa Conference League",
    "active": true,
    "short_code": "UEFA ECL",
    "image_path":
      "https://cdn.sportmonks.com/images/soccer/leagues/14/2286.png",
    "type": "league",
    "sub_type": "cup_international",
    "last_played_at": "2023-09-21 19:00:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 9,
    "sport_id": 1,
    "country_id": 462,
    "name": "Championship",
    "active": true,
    "short_code": "UK Champ",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/9/9.png",
    "type": "league",
    "sub_type": "domestic",
    "last_played_at": "2023-10-03 19:00:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 5,
    "sport_id": 1,
    "country_id": 41,
    "name": "Europa League",
    "active": true,
    "short_code": "UEFA EL",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/5/5.png",
    "type": "league",
    "sub_type": "cup_international",
    "last_played_at": "2023-09-21 19:00:00",
    "category": 1,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
  {
    "id": 24,
    "sport_id": 1,
    "country_id": 462,
    "name": "FA Cup",
    "active": true,
    "short_code": "UK FA Cup",
    "image_path": "https://cdn.sportmonks.com/images/soccer/leagues/24/24.png",
    "type": "league",
    "sub_type": "domestic_cup",
    "last_played_at": "2023-10-03 18:45:00",
    "category": 2,
    "has_jerseys": false,
    "sport": {
      "id": 1,
      "name": "Football",
    },
  },
];
