export const sportmonksCountries = [
  {
    "id": 2,
    "continent_id": 1,
    "name": "Poland",
    "official_name": "Republic of Poland",
    "fifa_name": "POL",
    "iso2": "PL",
    "iso3": "POL",
    "latitude": "52.147850036621094",
    "longitude": "19.37775993347168",
    "borders": ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/pl.png",
  },
  {
    "id": 5,
    "continent_id": 7,
    "name": "Brazil",
    "official_name": "Federative Republic of Brazil",
    "fifa_name": "BRA",
    "iso2": "BR",
    "iso3": "BRA",
    "latitude": "-10.81045150756836",
    "longitude": "-52.97311782836914",
    "borders": [
      "ARG",
      "BOL",
      "COL",
      "GUF",
      "GUY",
      "PRY",
      "PER",
      "SUR",
      "URY",
      "VEN",
    ],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/br.png",
  },
  {
    "id": 11,
    "continent_id": 1,
    "name": "Germany",
    "official_name": "Federal Republic of Germany",
    "fifa_name": "GER",
    "iso2": "DE",
    "iso3": "DEU",
    "latitude": "51.20246505737305",
    "longitude": "10.382203102111816",
    "borders": ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/de.png",
  },
  {
    "id": 17,
    "continent_id": 1,
    "name": "France",
    "official_name": "French Republic",
    "fifa_name": "FRA",
    "iso2": "FR",
    "iso3": "FRA",
    "latitude": "46.63727951049805",
    "longitude": "2.3382623195648193",
    "borders": ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/fr.png",
  },
  {
    "id": 20,
    "continent_id": 1,
    "name": "Portugal",
    "official_name": "Portuguese Republic",
    "fifa_name": "POR",
    "iso2": "PT",
    "iso3": "PRT",
    "latitude": "39.64200973510742",
    "longitude": "-8.009422302246094",
    "borders": ["ESP"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/pt.png",
  },
  {
    "id": 32,
    "continent_id": 1,
    "name": "Spain",
    "official_name": "Kingdom of Spain",
    "fifa_name": "ESP",
    "iso2": "ES",
    "iso3": "ESP",
    "latitude": "40.396026611328125",
    "longitude": "-3.550692558288574",
    "borders": ["AND", "FRA", "GIB", "PRT", "MAR"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/es.png",
  },
  {
    "id": 38,
    "continent_id": 1,
    "name": "Netherlands",
    "official_name": "Netherlands",
    "fifa_name": "NED",
    "iso2": "NL",
    "iso3": "NLD",
    "latitude": "52.34225845336914",
    "longitude": "5.5281572341918945",
    "borders": ["BEL", "DEU"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/nl.png",
  },
  {
    "id": 41,
    "continent_id": 1,
    "name": "Europe",
    "official_name": "Europe",
    "fifa_name": null,
    "iso2": "EU",
    "iso3": null,
    "latitude": null,
    "longitude": null,
    "borders": [],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/eu.png",
  },
  {
    "id": 44,
    "continent_id": 7,
    "name": "Argentina",
    "official_name": "Argentine Republic",
    "fifa_name": "ARG",
    "iso2": "AR",
    "iso3": "ARG",
    "latitude": "-37.071964263916016",
    "longitude": "-64.85450744628906",
    "borders": ["BOL", "BRA", "CHL", "PRY", "URY"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/ar.png",
  },
  {
    "id": 47,
    "continent_id": 1,
    "name": "Sweden",
    "official_name": "Kingdom of Sweden",
    "fifa_name": "SWE",
    "iso2": "SE",
    "iso3": "SWE",
    "latitude": "62.67497253417969",
    "longitude": "16.798059463500977",
    "borders": ["FIN", "NOR"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/se.png",
  },
  {
    "id": 62,
    "continent_id": 1,
    "name": "Switzerland",
    "official_name": "Swiss Confederation",
    "fifa_name": "SUI",
    "iso2": "CH",
    "iso3": "CHE",
    "latitude": "46.80379867553711",
    "longitude": "8.222854614257812",
    "borders": ["AUT", "FRA", "ITA", "LIE", "DEU"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/ch.png",
  },

  {
    "id": 86,
    "continent_id": 1,
    "name": "Ukraine",
    "official_name": "Ukraine",
    "fifa_name": "UKR",
    "iso2": "UA",
    "iso3": "UKR",
    "latitude": "48.92656326293945",
    "longitude": "31.47578239440918",
    "borders": ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/ua.png",
  },
  {
    "id": 98,
    "continent_id": 4,
    "name": "Australia",
    "official_name": "Commonwealth of Australia",
    "fifa_name": "AUS",
    "iso2": "AU",
    "iso3": "AUS",
    "latitude": "-25.585241317749023",
    "longitude": "134.50411987304688",
    "borders": [],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/au.png",
  },
  {
    "id": 143,
    "continent_id": 1,
    "name": "Austria",
    "official_name": "Republic of Austria",
    "fifa_name": "AUT",
    "iso2": "AT",
    "iso3": "AUT",
    "latitude": "47.58843994140625",
    "longitude": "14.14021110534668",
    "borders": ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/at.png",
  },
  {
    "id": 227,
    "continent_id": 1,
    "name": "Russia",
    "official_name": "Russian Federation",
    "fifa_name": "RUS",
    "iso2": "RU",
    "iso3": "RUS",
    "latitude": "63.125186920166016",
    "longitude": "103.75398254394531",
    "borders": [
      "AZE",
      "BLR",
      "CHN",
      "EST",
      "FIN",
      "GEO",
      "KAZ",
      "PRK",
      "LVA",
      "LTU",
      "MNG",
      "NOR",
      "POL",
      "UKR",
    ],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/ru.png",
  },
  {
    "id": 251,
    "continent_id": 1,
    "name": "Italy",
    "official_name": "Italian Republic",
    "fifa_name": "ITA",
    "iso2": "IT",
    "iso3": "ITA",
    "latitude": "42.7669792175293",
    "longitude": "12.493823051452637",
    "borders": ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/it.png",
  },
  {
    "id": 266,
    "continent_id": 1,
    "name": "Croatia",
    "official_name": "Republic of Croatia",
    "fifa_name": "CRO",
    "iso2": "HR",
    "iso3": "HRV",
    "latitude": "45.444305419921875",
    "longitude": "15.734503746032715",
    "borders": ["BIH", "HUN", "MNE", "SRB", "SVN"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/hr.png",
  },
  {
    "id": 320,
    "continent_id": 1,
    "name": "Denmark",
    "official_name": "Kingdom of Denmark",
    "fifa_name": "DEN",
    "iso2": "DK",
    "iso3": "DNK",
    "latitude": "56.10176086425781",
    "longitude": "9.555907249450684",
    "borders": ["DEU"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/dk.png",
  },
  {
    "id": 338,
    "continent_id": 7,
    "name": "Peru",
    "official_name": "Republic of Peru",
    "fifa_name": "PER",
    "iso2": "PE",
    "iso3": "PER",
    "latitude": "-9.212532997131348",
    "longitude": "-74.422119140625",
    "borders": ["BOL", "BRA", "CHL", "COL", "ECU"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/pe.png",
  },
  {
    "id": 353,
    "continent_id": 7,
    "name": "Colombia",
    "official_name": "Republic of Colombia",
    "fifa_name": "COL",
    "iso2": "CO",
    "iso3": "COL",
    "latitude": "3.9976072311401367",
    "longitude": "-73.27796936035156",
    "borders": ["BRA", "ECU", "PAN", "PER", "VEN"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/co.png",
  },
  {
    "id": 404,
    "continent_id": 2,
    "name": "Turkey",
    "official_name": "Republic of Turkey",
    "fifa_name": "TUR",
    "iso2": "TR",
    "iso3": "TUR",
    "latitude": "39.05101013183594",
    "longitude": "34.93033981323242",
    "borders": ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/tr.png",
  },
  {
    "id": 458,
    "continent_id": 6,
    "name": "Mexico",
    "official_name": "United Mexican States",
    "fifa_name": "MEX",
    "iso2": "MX",
    "iso3": "MEX",
    "latitude": "23.909093856811523",
    "longitude": "-102.6333999633789",
    "borders": ["BLZ", "GTM", "USA"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/mx.png",
  },
  {
    "id": 462,
    "continent_id": 1,
    "name": "England",
    "official_name": "United Kingdom of Great Britain and Northern Ireland",
    "fifa_name": "ENG,NIR,SCO,WAL",
    "iso2": "GB",
    "iso3": "GBR",
    "latitude": "54.56088638305664",
    "longitude": "-2.2125117778778076",
    "borders": ["IRL"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/gb.png",
  },
  {
    "id": 556,
    "continent_id": 1,
    "name": "Belgium",
    "official_name": "Kingdom of Belgium",
    "fifa_name": "BEL",
    "iso2": "BE",
    "iso3": "BEL",
    "latitude": "50.648963928222656",
    "longitude": "4.641502380371094",
    "borders": ["FRA", "DEU", "LUX", "NLD"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/be.png",
  },
  {
    "id": 1161,
    "continent_id": 1,
    "name": "Scotland",
    "official_name": "United Kingdom of Great Britain and Northern Ireland",
    "fifa_name": "ENG,NIR,SCO,WAL",
    "iso2": "GB",
    "iso3": "GBR",
    "latitude": "54.56088638305664",
    "longitude": "-2.2125117778778076",
    "borders": ["IRL"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/scotland.png",
  },
  {
    "id": 1578,
    "continent_id": 1,
    "name": "Norway",
    "official_name": "Kingdom of Norway",
    "fifa_name": "NOR",
    "iso2": "NO",
    "iso3": "NOR",
    "latitude": "66.76667022705078",
    "longitude": "14.899925231933594",
    "borders": ["FIN", "SWE", "RUS"],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/no.png",
  },
  {
    "id": 5618,
    "continent_id": 2,
    "name": "China",
    "official_name": "People's Republic of China",
    "fifa_name": "CHN",
    "iso2": "CN",
    "iso3": "CHN",
    "latitude": "36.55308532714844",
    "longitude": "103.97543334960938",
    "borders": [
      "AFG",
      "BTN",
      "MMR",
      "HKG",
      "IND",
      "KAZ",
      "PRK",
      "KGZ",
      "LAO",
      "MAC",
      "MNG",
      "PAK",
      "RUS",
      "TJK",
      "VNM",
    ],
    "image_path":
      "https://cdn.sportmonks.com/images/countries/png/short/cn.png",
  },
];
